"""Diagnostic warning enum covering all layers."""

from enum import Enum


class DiagnosticWarning(str, Enum):
    # Layer 2 -- Degradation
    UNKNOWN_DEGRADATION_LABEL = "UNKNOWN_DEGRADATION_LABEL"

    # Layer 3 -- Diagnostics
    SPATIAL_BLEED = "SPATIAL_BLEED"
    NO_TRANSFER_SIGNAL = "NO_TRANSFER_SIGNAL"
    WEAK_SOLVER = "WEAK_SOLVER"
    UNEXPLAINED_SPATIAL_PATTERN = "UNEXPLAINED_SPATIAL_PATTERN"
    COLLAPSE_RISK = "COLLAPSE_RISK"
    LOW_COHERENCE = "LOW_COHERENCE"

    # Layer 4 -- Trajectory
    TRAJECTORY_REGRESSION = "TRAJECTORY_REGRESSION"
    SIGMA_DESTABILIZING = "SIGMA_DESTABILIZING"
    PREMATURE_STALL = "PREMATURE_STALL"
    PROVENANCE_MISMATCH = "PROVENANCE_MISMATCH"

    # Layer 5 -- Routing / Conflict
    ADMISSION_REPLAY_MISMATCH = "ADMISSION_REPLAY_MISMATCH"
    ROUTING_CONFLICT = "ROUTING_CONFLICT"

    # Loader
    MISSING_CERTIFICATE_METRIC = "MISSING_CERTIFICATE_METRIC"
    UNKNOWN_GATE_ENUM = "UNKNOWN_GATE_ENUM"
    DUPLICATE_PHASE = "DUPLICATE_PHASE"
    DUPLICATE_CELL = "DUPLICATE_CELL"
    MALFORMED_JSON = "MALFORMED_JSON"
    MISSING_PHASE = "MISSING_PHASE"
