#!/usr/bin/env python3
"""launch_compute_gearbox_warmup.py -- Phase 0.75: Gearbox warmup pass.

Runs Ridge CV on all (scenario, target) cells to produce data-grounded
quality signals (tau, sigma, alpha_warmup, collapse_risk, coherence)
and calibrated gear boundaries for DGM routing + oobleck autocalibration.

Requires: folds generated by Phase 1 (train_r0_baseline --upload).
Outputs:  gearbox_warmup.json on S3.

Resource: ml.m5.large (2 vCPU, 8 GB). Ridge CV is cheap.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _launcher_base import launch_processing_job, make_job_name


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    job_name = make_job_name("gearbox-warmup")

    extra = [str(Path(__file__).parent.parent / "jobs" / "generate_folds.py")]

    launch_processing_job(
        job_name=job_name,
        job_script="compute_gearbox_warmup.py",
        job_args=["--upload"],
        instance_type="ml.m5.large",
        volume_size_gb=10,
        pip_packages="scipy scikit-learn",
        extra_files=extra,
        dry_run=args.dry_run,
        phase_id="gearbox_warmup",
    )


if __name__ == "__main__":
    main()
